#!/bin/bash
docker rm -f mbm
export GOROOT=/usr/local/go
export GOPATH=$(pwd)/..
/usr/local/go/bin/go get golang.org/x/text/encoding/charmap
/usr/local/go/bin/go test -coverprofile ../front/public/cover/mailbox.out mailbox
/usr/local/go/bin/go tool cover -html=../front/public/cover/mailbox.out -o ../front/public/cover/mailbox.html
/usr/local/go/bin/go install mbm
cp ../bin/mbm mbm
docker build -f Dockerfile.$1 -t mbm .
MBM_PORT="8080"
if [ "$5" != "" ]; then
    MBM_PORT=$5
fi
docker run --name mbm --volumes-from cdc --volumes-from mbs -p $MBM_PORT:8080 -h mbm -d -t mbm
docker cp /usr/bin/uuidgen mbm:/usr/bin/uuidgen
