#!/bin/bash
docker rm -f postfix
cp main.cf.dist main.cf
sed -i s/mail.local/$2/g main.cf
docker build -f Dockerfile.$1 -t postfix .
docker run --name postfix --volumes-from cdc --volumes-from mbs -d -p 25:25 -t postfix

