FROM ubuntu
RUN apt-get update && apt-get install -y postfix
ADD main.cf /etc/postfix/main.cf
ENTRYPOINT postmap /var/www/data/vmailbox && /etc/init.d/rsyslog start && postfix start && tail -F /var/log/mail.log
EXPOSE 25