FROM armbuild/ubuntu
RUN apt-get update && apt-get install -y postfix && apt-get install nano
ADD /main.cf /etc/postfix/main.cf
ADD /master.cf /etc/postfix/master.cf
ENTRYPOINT postmap /var/www/data/vmailbox && /etc/init.d/rsyslog start && postfix start && tail -F /var/log/mail.log
EXPOSE 25