#!/bin/bash
docker rm -f cdc
export GOROOT=/usr/local/go
export GOPATH=$(pwd)/..
/usr/local/go/bin/go run ../src/pvbm/pvbm.go -domain=$2 -count=10000 -length=3 > vmailbox
docker build -f Dockerfile.$1 -t cdc .
docker run --name cdc -t cdc
