#!/bin/bash
docker rm -f mmlnginx
cp default.conf.dist default.conf
MBMIP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' mbm)
docker build -f Dockerfile.$1 -t mmlnginx .
docker run --name mmlnginx --add-host mbm:$MBMIP --volumes-from front -p 80:80 -d -t mmlnginx
