#!/bin/bash
docker rm -f nginx
cp default.conf.dist default.conf
MBMIP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' mbm)
docker build -f Dockerfile.$1 -t nginx .
docker run --name nginx --add-host mbm:$MBMIP --volumes-from front -p 80:80 -d -t nginx
