#!/bin/bash
docker rm -f front
wget --output-document public/js/jquery-1.12.0.min.js --quiet http://code.jquery.com/jquery-1.12.0.min.js
wget --output-document public/js/jquery-2.1.4.min.js --quiet http://code.jquery.com/jquery-2.1.4.min.js
wget --output-document public/css/bootstrap.min.css --quiet https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
docker build -f Dockerfile.$1 -t front .
docker run --name front -t front
